version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ai_blog_web
    command: /start-server
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
  
  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ai_blog_celery
    command: /start-worker
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
  
  celery_beat:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ai_blog_celery_beat
    command: /start-beat
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
