# Generated by Django 5.0.7 on 2024-07-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='response',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_response',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CommentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.comment')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blog.comment')),
            ],
        ),
    ]
