# Generated by Django 5.0.7 on 2024-07-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_response_comment_is_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentresponse',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='commentresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='blog.comment'),
        ),
    ]
