# Generated by Django 5.0.7 on 2024-07-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentresponse_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentresponse',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
    ]
