# Generated by Django 5.0.7 on 2024-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
