# Generated by Django 5.0.7 on 2024-07-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auto_post_reply',
            field=models.PositiveIntegerField(blank=True, help_text='minutes', null=True),
        ),
    ]
