# Generated by Django 5.0.7 on 2024-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_auto_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auto_post_reply',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='minutes', null=True),
        ),
    ]
